project:
  type: website

website:
  title: "Sarah Liu"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sarah-liu17
      - icon: linkedin
        text: Linkedln
        href: https://www.linkedin.com/in/sarah-liu-b27362260/
      - icon: instagram
        text: Instagram
        href: https://www.instagram.com/2002_sarah/
format:
  html:
    theme: flatly
    css: styles.css



